In [1]:
from scipy.io import loadmat
annots = loadmat('ex8_movies.mat')

annots

{'__header__': b'MATLAB 5.0 MAT-file, Platform: GLNXA64, Created on: Thu Dec  1 17:19:26 2011',
 '__version__': '1.0',
 '__globals__': [],
 'Y': array([[5, 4, 0, ..., 5, 0, 0],
        [3, 0, 0, ..., 0, 0, 5],
        [4, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
 'R': array([[1, 1, 0, ..., 1, 0, 0],
        [1, 0, 0, ..., 0, 0, 1],
        [1, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)}

In [2]:
import numpy as np 
import pandas as pd 
from matplotlib import pyplot as plt

data = dict()

In [3]:
for key, item in annots.items():
    if key=='Y' or key=='R':
        data[key]=item

data 

{'Y': array([[5, 4, 0, ..., 5, 0, 0],
        [3, 0, 0, ..., 0, 0, 5],
        [4, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint8),
 'R': array([[1, 1, 0, ..., 1, 0, 0],
        [1, 0, 0, ..., 0, 0, 1],
        [1, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)}

In [4]:
a=np.array([[2,3],[4,5]])

b=np.transpose(a.copy())
print(a)
print(b)

[[2 3]
 [4 5]]
[[2 4]
 [3 5]]


In [5]:
print(a-b)
print('\n')

print(a.sum())
print('\n')

print(a*a)
print('\n')
print(5*a)
print('\n')

j=[]
i=[]
j.append(1.5)
i.append(1)
print(j)
print(i)

[[ 0 -1]
 [ 1  0]]


14


[[ 4  9]
 [16 25]]


[[10 15]
 [20 25]]


[1.5]
[1]


In [6]:
#concatenating and reshaping the matrices

x=np.array([[1,2,3],[4,5,6]])
y=np.array([[7,8,9],[10,11,12]])

z=np.concatenate((x,y), axis=None)

print(x)
print(y)
print(z)
print('\n')

z=z+1;
x, y = z[:6,], z[6:,]
x=np.reshape(x, (2,3))
y=np.reshape(y, (2,3))
print(x)
print(y)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


[[2 3 4]
 [5 6 7]]
[[ 8  9 10]
 [11 12 13]]


In [7]:
my_ratings = np.zeros((1682, 1), dtype=float)
my_ratings.shape 

(1682, 1)

In [13]:
my_ratings[7] = 3;
my_ratings[12]= 5;
my_ratings[54] = 4;
my_ratings[64]= 5;
my_ratings[66]= 3;
my_ratings[69] = 5;
my_ratings[183] = 4;
my_ratings[226] = 5;
my_ratings[355]= 5;
my_ratings[1] = 4;
my_ratings[2] = 4;

#generating user y vector from the user ratings
my_y = (my_ratings!=0)*1
print(my_y)

my_inv_y = (my_y -1)*-1 
print(my_inv_y)

[[0]
 [1]
 [1]
 ...
 [0]
 [0]
 [0]]
[[1]
 [0]
 [0]
 ...
 [1]
 [1]
 [1]]


In [9]:
with open('movie_ids.txt') as f:
    movieList = [line.rstrip('\n') for line in f]
movieList[0]

'1 Toy Story (1995)'

In [10]:
l = np.ones((7,1), dtype=float)
l2 = np.zeros((7, 5), dtype=float)
#np.concatenate((l,l2), axis=1)
l3 = np.hstack((l,l2))
m,n = l3.shape
print(m)
print(n)

7
6
